services:
  spring_app:
    container_name: spring_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - API_SERVICE_KEY=LX1Fa5ExG4QlJxkuPAQj8DYylJiU1O1b40lWB0K4uk%2F%2FMjcRGyU5YJNBsFJxFhZ2PY49hPWeyZbQrMkKUEH6kA%3D%3D
      - SPRING_APPLICATION_NAME=air
      - SERVER_PORT=8080
      - SPRING_MVC_VIEW_PREFIX=/WEB-INF/views/
      - SPRING_MVC_VIEW_SUFFIX=.jsp
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./:/app
      - gradle_cache:/root/.gradle

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  gradle_cache: