spring:
  application:
    name: air
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    async:
      request-timeout: -1  # SSE 연결 타임아웃 비활성화
  web:
    resources:
      static-locations: classpath:/static/
  threads:
    virtual:
      enabled: true

api:
  airquality:
    serviceKey: LX1Fa5ExG4QlJxkuPAQj8DYylJiU1O1b40lWB0K4uk%2F%2FMjcRGyU5YJNBsFJxFhZ2PY49hPWeyZbQrMkKUEH6kA%3D%3D

logging:
  level:
    com.example.air: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.view: TRACE